[package]
name = "bronze_kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
bootloader_api = "0.11"
x86_64 = "0.15.4"
lazy_static = { version = "1.5.0", default-features = false, features = ["spin_no_std"] }
spin = "0.12.0"

[[bin]]
name = "bronze_kernel"
path = "src/main.rs"
harness = false